### ISSUE TITLE
Rename to `@comapeo/schema` and release v1

### ISSUE THREAD

**Issue by gmaclennan** [digidem/comapeo-schema#194]
MVP should ship with v1.0.0 schema, so we have clear version control going forwards.

**Comment by tomasciccola** [comment]
Steps for this should be:
1. Create a new repo (comapeo-schema)
2. Push the current state of mapeo-schema to that repo without any tags
3. add that repo to npm @comapeo org and publish as `@comapeo/schema` (this needs someone with access to @comapeo org)
4. migrate all issues and PRs?
5. Create a release with version 1.0.0
